name: premake5-windows

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/premake5-windows.yml'
      - 'premake5.lua'

  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/premake5-windows.yml'
      - 'premake5.lua'

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: checkout premake5
      uses: actions/checkout@v3
      with:
        repository: premake/premake-core
        path: premake-build

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Build premake5
      run: |
        $vcvarall_path = vswhere -find VC\Auxiliary\Build\vcvarsall.bat
        cmd.exe /c "call ""$vcvarall_path"" x86_amd64 && cd premake-build && nmake -f Bootstrap.mak MSDEV=vs2022 windows-msbuild PLATFORM=Win32 CONFIG=release"
        cp premake-build/bin/release/premake5.exe ./

    - name: run premake5
      run: ./premake5.exe vs2022 to=solution/vs2022/resinstaller

    - name: build
      run: |
        cd solution/vs2022/resinstaller
        nuget install packages.config -OutputDirectory packages
        msbuild.exe /property:Configuration=Release Resinstaller.sln

    - name: upload resinstaller.exe
      uses: actions/upload-artifact@v3
      with:
        name: resinstaller
        path: solution/vs2022/resinstaller/bin/Release
