name: Check Markdown links

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/check-links.yml'
      - '**/*.md'

  pull_request:
    paths:
      - '.github/workflows/check-links.yml'
      - '**/*.md'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
