name: macos

on:
  workflow_dispatch:
  push:
    paths:
      - 'resinstaller/src/**'
      - 'src/**'
      - 'submodules/**'
      - 'test/**'
      - '.github/workflows/macos.yml'
      - 'CMakeLists.txt'
      - 'mk/cmake/**'

  pull_request:
    paths:
      - 'resinstaller/src/**'
      - 'src/**'
      - 'submodules/**'
      - 'test/**'
      - '.github/workflows/macos.yml'
      - 'CMakeLists.txt'
      - 'mk/cmake/**'

jobs:
  macos:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: install dependencies
      run: brew install sdl2 sdl2_mixer sdl2_net libogg libvorbis

    - name: cmake --version
      run: cmake --version

    - name: test projects
      run: |
        mkdir build && cd build
        cmake ..
        make maxr_dedicatedserver maxr maxr_tests resinstaller -j4
        ./maxr_tests

