name: premake5-msys2-windows

on:
  workflow_dispatch:
  push:
    paths:
      - 'resinstaller/**'
      - 'src/**'
      - 'submodules/**'
      - 'test/**'
      - '.github/workflows/premake5-msys2-windows.yml'
      - 'premake5.lua'

  pull_request:
    paths:
      - 'resinstaller/**'
      - 'src/**'
      - 'submodules/**'
      - 'test/**'
      - '.github/workflows/premake5-msys2-windows.yml'
      - 'premake5.lua'

jobs:
  windows:
    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          make
          gcc
          python3
          mingw-w64-x86_64-SDL2
          mingw-w64-x86_64-SDL2_net
          mingw-w64-x86_64-SDL2_mixer
          mingw-w64-x86_64-libvorbis
          mingw-w64-x86_64-libogg

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
        fetch-tags: true

    - name: install premake5
      uses: Jarod42/install-premake5@v5

    - name: Retrieve CrashRpt_v.1.4.3_r1645
      run: |
        curl -o CrashRpt_v.1.4.3_r1645.7z -L https://sourceforge.net/projects/crashrpt/files/CrashRpt_v.1.4.3_r1645.7z/download
        7z x -o"./CrashRpt_v.1.4.3_r1645" "CrashRpt_v.1.4.3_r1645.7z" "lib/*.*" "include/*.*" "bin/CrashRpt1403.dll" "bin/CrashSender1403.exe" "bin/crashrpt_lang.ini"
        7z e -o"data/CrashRpt"          CrashRpt_v.1.4.3_r1645.7z "lang_files/*.ini"

    - name: run premake5
      shell: msys2 {0}
      run: |
        "/C/Program Files/premake/premake5.exe" gmake --to=solution/gmake --crashRpt_root=CrashRpt_v.1.4.3_r1645

    - name: build
      shell: msys2 {0}
      run: |
        cd solution/gmake
        make

    - name: run tests
      run: |
        cd solution/gmake/bin/Release
        ./maxr_tests.exe

    - name: prepare for upload # upload-artifact requires a common root path
      shell: msys2 {0}
      run: |
        cd data
        python mingw_deploy.py maxr.exe

    - name: upload maxr
      uses: actions/upload-artifact@v4
      with:
        name: maxr
        path: |
          data/**.exe
          data/**.dll

