name: resinstaller-macos

on:
  workflow_dispatch:
  push:
    paths:
      - 'resinstaller/src/**'
      - '.github/workflows/resinstaller-macos.yml'
      - 'resinstaller/CMakeLists.txt'

  pull_request:
    paths:
      - 'resinstaller/src/**'
      - '.github/workflows/resinstaller-macos.yml'
      - 'resinstaller/CMakeLists.txt'

jobs:
  macos:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: install dependencies SDL2 ogg vorbis
      run: brew install sdl2 libogg libvorbis

    - name: cmake --version
      run: cmake --version

    - name: build project
      run: |
        mkdir build && cd build
        cmake ../resinstaller && cmake --build .

