name: ubuntu

on:
  workflow_dispatch:
  push:
    paths:
      - 'resinstaller/src/**'
      - 'src/**'
      - 'test/**'
      - '.github/workflows/ubuntu.yml'
      - 'CMakeLists.txt'
      - 'mk/cmake/**'

  pull_request:
    paths:
      - 'resinstaller/src/**'
      - 'src/**'
      - 'test/**'
      - '.github/workflows/ubuntu.yml'
      - 'CMakeLists.txt'
      - 'mk/cmake/**'

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: apt-get update
      run: sudo apt-get update

    - name: install dependencies
      run: |
        sudo apt-get install libsdl2-dev libsdl2-mixer-dev libsdl2-net-dev libogg-dev libvorbis-dev libvorbisenc2 libvorbisidec-dev

    - name: cmake --version
      run: cmake --version

    - name: test projects
      run: |
        mkdir build && cd build
        cmake ..
        make maxr_dedicatedserver maxr maxr_tests resinstaller -j4
        ./maxr_tests

